### PR TITLE
Update wrapperinstancesetup.md

### PR DESCRIPTION
**Pull request by soumith**
added missing info on nimbix wrapper

### CODE REVIEW

**Comment by soumith** [comment]
So, this still does not seem to work when I run:

curl -d 'h=123&s=[secretstuff]' "http://$WRAPPER_IP/run"

**Comment by soumith** [comment]
i'll try to debug why...
I sent you the wrapper's IP and key via email as well just in case.

**Comment by hughperkins** [comment]
I normally test direclty from github. it shows the output and so on, and it does the exact call you need.

**Comment by hughperkins** [comment]
oh wait... I think I need to revise a sec :-)

**Comment by soumith** [comment]
i figured out the issue. ec2 internal IP of JENKINS_IP is different from external.

**Comment by hughperkins** [comment]
ah, right :-)

**Comment by soumith** [comment]
now all works a bit further.

curl -d 'h=123&s=[secret]' "http://$WRAPPER_IP:3237/run"

When I run the tester curl command, encounter this error:

```
$ bash start.sh
DEBUG:__main__:doing ftp...
/home/ubuntu/nimbix-admin/env/lib/python3.4/site-packages/pysftp/__init__.py:61: UserWarning: Failed to load HostKeys from /home/ubuntu/.ssh/known_hosts.  You will need to explicitly load HostKeys (cnopts.hostkeys.load(filename)) or disableHostKey checking (cnopts.hostkeys = None).
  warnings.warn(wmsg, UserWarning)
ERROR:__main__:No hostkey for host drop.jarvice.com found.
Traceback (most recent call last):
  File "wrapper-service/nimbix-wrapper.py", line 84, in run
    with pysftp.Connection(drop_host, username=username, password=apikey) as sftp:
  File "/home/ubuntu/nimbix-admin/env/lib/python3.4/site-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/home/ubuntu/nimbix-admin/env/lib/python3.4/site-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
paramiko.ssh_exception.SSHException: No hostkey for host drop.jarvice.com found.
Exception ignored in: <bound method Connection.__del__ of <pysftp.Connection object at 0x7fccbf806a58>>
Traceback (most recent call last):
  File "/home/ubuntu/nimbix-admin/env/lib/python3.4/site-packages/pysftp/__init__.py", line 1013, in __del__
    self.close()
  File "/home/ubuntu/nimbix-admin/env/lib/python3.4/site-packages/pysftp/__init__.py", line 784, in close
    if self._sftp_live:
AttributeError: 'Connection' object has no attribute '_sftp_live'
```

**Comment by hughperkins** [comment]
(not related to the issue; but I think we should `sudo apt-get upgrade` the jenkins instance; I'll do that now)

**Comment by hughperkins** [comment]
(done the apt-get upgrade on the jenkins)

**Comment by soumith** [comment]
i have to sign off in 10 mins, but will look at messages in a few hours again. 
should I start doing https://github.com/hughperkins/torchunit/blob/master/githubconfiguration.md while you fix this stuff?

**Comment by soumith** [comment]
also, in NIMBIX, right now I dont have any ssh keys setup in "Manage SSH Keys". I presume I have to do something there, should I create a new key?

**Comment by soumith** [comment]
screen shot 2016-08-29 at 7 51 38 pm

**Comment by hughperkins** [comment]
> should I start doing https://github.com/hughperkins/torchunit/blob/master/githubconfiguration.md 

I cant remember, it was a while ago  iwrote it :-P  I guess you can check what the pre-requisites are and stuff?

**Comment by hughperkins** [comment]
> I presume I have to do something there, should I create a new key?

Seems I have one in mine, so I think so.

**Comment by hughperkins** [comment]
(the error above is about ftp'ings to the drop.jarvice.com sftp host, which is done to inject a script there, that will be later run by the job.  The job will run the script from drop.jarvice.com, which is mounted at `/data` on the instance.  It seems plausible that this is because of missing hte ssh key)

**Comment by hughperkins** [comment]
hmmm, no, it uses the apikey for sftp, like, you can see in the stacktrace above:

```
with pysftp.Connection(drop_host, username=username, password=apikey) as sftp
```

**Comment by hughperkins** [comment]
Is it because have to first ssh once ot the host, an daccept the hostkey?

**Comment by hughperkins** [comment]
I did `ssh drop.jarvice.com` from the wrapper host, and accepted the hostkey.  I think the error about hostkey has gone away now right?

**Comment by soumith** [comment]
yes, so i just added the ssh keys, the error seems to have gone away after this...

**Comment by hughperkins** [comment]
see my comment just before yours :-)

**Comment by soumith** [comment]
ohh i see, that's why... :)

**Comment by soumith** [comment]
okay now I'm getting this:

bash start.sh
DEBUG:**main**:doing ftp...
DEBUG:**main**:... ftp done
DEBUG:**main**:launch_data {"vault": {"force": false, "name": "drop.jarvice.com", "readonly": false}, "machine": {"nodes": "1", "type": "ngd3"}, "user": {[redacted]}, "nae": {"force": false, "command": "bash /data/~job.sh", "name": "ngd3", "staging": true, "ephemeral": false, "interactive": false, "walltime": "0:40:00"}}
INFO:**main**:200 b'{\n    "name": "20160830000047-CLK6N-NAE-soumith_s1", \n    "number": 128069\n}\n'
DEBUG:**main**:jobnumber 128069
Failed to map NAE, which may be locked.
If you believe this lock is stale, try again with
the "Force" option.

IMPORTANT NOTE 1: using the "Force" option on an NAE that
    is already running _WILL_ result in data corruption!
    Please use extreme caution when specifying "Force"!

IMPORTANT NOTE 2: if you are attempting to start a locked
    staging NAE in ephemeral mode, this may fail in some
    cases even if you use the "Force" option.  Please try
    again after either shutting down the existing staging
    NAE, or starting a single (not parallel) staging NAE
    with the "Force" option (please see IMPORTANT NOTE 1)

**Comment by soumith** [comment]
also i'm getting a bunch of emails :)
screen shot 2016-08-29 at 8 04 12 pm

**Comment by soumith** [comment]
so something's working ha!

**Comment by soumith** [comment]
ok i have to sign off now.
The "bash start.sh" is running in tmux 0

**Comment by hughperkins** [comment]
Yeah, the mails are kind of annoying.  I created a filter to just pipe them all to /dev/null... (I mean, on my own email)

**Comment by soumith** [comment]
the ssh keys are now added to my account. See ~/.ssh/id_rsa or id_rsa.pub on either the jenkins machine or the wrapper machine (copied to both)
screen shot 2016-08-29 at 8 06 55 pm

**Comment by hughperkins** [comment]
ok. What image(s) are created?

**Comment by hughperkins** [comment]
(images are basically containers, equivalent to vms)

**Comment by soumith** [comment]
screen shot 2016-08-29 at 8 09 51 pm
screen shot 2016-08-29 at 8 09 47 pm

**Comment by soumith** [comment]
as you instructed, i created t1.

**Comment by hughperkins** [comment]
k, sounds good

**Comment by hughperkins** [comment]
ah, in the config.yaml, we should put `image: t1`

**Comment by hughperkins** [comment]
(I've modified, and restarted the start.sh)

**Comment by hughperkins** [comment]
getsabitfurthernow

**Comment by hughperkins** [comment]
(presumably we need to install git onto the nimbix container t1)

**Comment by hughperkins** [comment]
(added `sudo apt-get install -y git` to config.yaml , restarted start.sh , and redid curl)

**Comment by hughperkins** [comment]
I think it got as far as its supposed to go for now :-P
resultsnow

**Comment by hughperkins** [comment]
this is basically the output of running: https://github.com/hughperkins/torchunit/blob/master/nimbix-bootstrap.sh

**Comment by hughperkins** [comment]
(and `123` is waht we passed into the curl)

**Comment by hughperkins** [comment]
(feel free to fork this repo by the way, and point stuff to the fork)

**Comment by soumith** [comment]
alright, so i setup the webhook now as well. let's see what happens

**Comment by soumith** [comment]
do i have to start jenkins on the server etc.?

**Comment by soumith** [comment]
nevermind, jenkins is already started.
I am not able to login to jenkins.
Username: admin
password: [the jenkins password in config.yaml]

But I get:
screen shot 2016-08-30 at 4 17 15 pm

**Comment by soumith** [comment]
figured it out.

username: jenkins

**Comment by soumith** [comment]
okay i came much further.
I reinstalled jenkins for some reason, so whatever stuff you setup looks like it was lost.
I also forked torchunit and nimbix-admin into github.com/torch

Now I have a question.
When I trigger @torchbot , it kicks off a build and runs this script: https://github.com/torch/torchunit/blob/master/jenkins/cutorch/build.sh
Which is empty of course.
I'm not sure how this script can call the nimbix-wrapper and trigger a build on nimbix.
Can I get some guidance on that?

**Comment by soumith** [comment]
i think i've tracked things down quite a bit.
From my understanding,
1. Jenkins calls https://github.com/hughperkins/torchunit/blob/master/jenkins/cutorch/build.sh
   with variables like these:
   GIT_COMMIT=b32cf5ff2edee18fb41c2c146d75c556fed7cc8a
   GIT_BRANCH=origin/pr/490/merge
   GIT_URL=https://github.com/torch/cutorch
2. the build.sh which I am working on modifying, should call:
   curl -d 'h=$GIT_COMMIT&s=[secret]' "http://$WRAPPER_IP:3237/run"
   I need to add, apart from h and s parameters, also branch and url parameters.
   I need to modify this file: https://github.com/torch/nimbix-admin/blob/master/wrapper-service/nimbix-wrapper.py
3. After that, the nimbix wrapper will launch a nimbix instance, and launch https://github.com/hughperkins/torchunit/blob/master/nimbix-bootstrap.sh with the arguments.

Then I need to figure out how to pass the logs back from nimbix all the way to the jenkins. a possible option is to POST back the logs + return code. Also have to modify nimbix-wrapper.py to enable this.

**Comment by hughperkins** [comment]
havent read your comments yet, but notice that I think the script I wrote for creating the self-signed is wrong.  the numbr of newlines is not quite right, so the url is ending up in OU, instead of in common-name.

this, in installjenkins.sh:

```
cat <<EOF>infile
US



jenkins.torch.ch




EOF
```

should be

```
cat <<EOF>infile
US




jenkins.torch.ch



EOF
```

(ie 4 blank lines, then 3 instead of 3 blank lines instead of 4).  so probably need to recreate the cert.  (This might not have any impact unless we try connecting any agent nodes though, which I dont think we have, at the moment)

**Comment by hughperkins** [comment]
The logs should pass back automatically already.  You can see that the output of nimbix-bootstrap.sh ends up coming back to your `curl` command output right?

**Comment by hughperkins** [comment]
> I need to add, apart from h and s parameters, also branch and url parameters.

I'm not very keen on passing the url as a parameter, because then someone could pass in a fake url.  I cant quite remember what my plan was though.  Was the plan to hard-code the url in the nimbix-boostrap.sh ? I cant quite remember.  I guess you're thinking that since you want to generalize this to work for both cutorch and cunn, so it should be confiurable?

**Comment by hughperkins** [comment]
Perhaps you can pass in the name of the repo, eg `cutorch` or `cunn` as the parameter, make sure to strip out anything non-alpha inside the receiving script, and then generate the url from this, since it will always start with `https://github.com/torch/` ?

**Comment by hughperkins** [comment]
Ok, I think the comment where I "thought through" the wrapper bit was https://github.com/torch/cutorch/issues/390#issuecomment-230177250 and it says:

```
- only runs some very specific script, from some specific repo, albeit with a (cleaned) parameter, being probably the git commit hash
   -  eg might run a script from eg torchunit repo, called eg nimbix-bootstrap, on the launched titan x instance, and it will pass in the git commit hash as a parameter
   -  the parameter should be cleaned to ensure it only contains a-f and digits 0-9, and no more than 40 characters long
```

It looks like I didnt think very far about generlizing to build bot hcutorch and cunn.  I think that a safe-ish appraoch might be to add one additional parameter, being the repo name, pure alpha, and the wrapper script should clean it to ensure that it only contains a-z, and no more than say 32 characters long.

**Comment by soumith** [comment]
> Perhaps you can pass in the name of the repo, eg cutorch or cunn as the parameter, make sure to strip out anything non-alpha inside the receiving script, and then generate the url from this, since it will always start with https://github.com/torch/ ?

Yes, i'll modify it to do this. Seems better.

**Comment by hughperkins** [comment]
Hmmm, I just noticed the non-pc naming I was giving to agent nodes, in my comment of https://github.com/hughperkins/torchunit/pull/1#issuecomment-243622736  So, I woke up resolved to file a PR against upstream jenkins to fix this, but then noticed it's already done, and they're now called 'agents', but we need to upgrade.  2.7.2 calls them 'agents'.  http://mirrors.jenkins-ci.org/war-stable/2.7.2/jenkins.war

**Comment by hughperkins** [comment]
(by the way, for logs, and test output pass/fail, in the first instance, simply using the output of `curl` is probably good.  not sure how to check it failed. maybe just grep for words like `FAIL` or `ERROR`?  keeping it simple.

in a later version, a more sustainable/mature approach might be to output the tests results in eg junit xml format, and add a `post-build` step to the jenkins, which reads this xml file.  The xml file can be transported from nimbix instance to jenkins via drop.jarvice.com, to which we already sftp our script, and we can simply sftp the results back too. (or pass it back in the post response could work too; not sure which is easier really?)
)

**Comment by hughperkins** [comment]
small detail, as far as nimbix types, there are a few options (I sipmlified above by just putting down ngd3, ie dual titan x):
- ng0 half a titan x, on bfboost, 0.5usd/hour
- ng1 full titan x, via bfboost, 1usd/hour
  - for bfboost, you have to prefix any commands with `bfboost client -r`
  - eg `bfboost client -r th train.lua`
  - (it works with opencl too by the way)
- ngd3 dual titan x, non-bfboost (3usd/hour) (I use for benchmarking, just to be sure, but in practice the times I get on ng1 are identical, with a slight 1-3 second startup initial latency as the gpu is located and connected)
  - these are a bit in high demand recently though, so...
- ng6 is a pretty good option, if want non-bfboost, which is a 1080 (2usd/hour)

On the whole, ng1 is probably good for, well, many/most things actually.

**Comment by soumith** [comment]
yea i noticed those.
btw, i succesfully setup cutorch contbuilds last night: http://50.17.86.9:8080/job/cutorch/33/console

I only have a small bug in the error code stuff, but everything else is good :)

**Comment by hughperkins** [comment]
Oh, nice! :-)

**Comment by hughperkins** [comment]
(By the way, there is https available at 8443 .  Probably good for logging on and stuff, although you have to accept the self-signed warning)

**Pull request merged**
